parser = HrmParser()
print(parser.parse_line("  command crisp_bacon"))
print(parser.parse_line("command   crisp_bacon  "))
print(parser.parse_line("  "))
print(parser.parse_line("command"))
print(parser.parse_line("  command 7"))
print(parser.parse_line("  command a_7"))
print(parser.parse_line("  command 1 2 3 4 5"))
print(parser.parse_line("  command %#@$"))
print(parser.parse_line("  command y"))
print(parser.parse_line(":foo"))
print(parser.parse_line(":foo_1"))
print(parser.parse_line(":1"))
print(parser.parse_line(":foo badarg"))
print(parser.parse_line("   # comment"))
print(parser.parse_line("# comment"))
print(parser.parse_jumptag("test"))
print(parser.parse_jumptag(":test"))
print(parser.parse_jumptag(":1"))
print(parser.parse_jumptag(":test1"))
print(parser.parse_jumptag(":test  ") + "x")
print(parser.parse_jumptag(":_test"))
print(parser.parse_jumptag(":test_test"))
print(parser.parse_jumptag(":test_11"))
print(parser.parse_memref("5"))
print(parser.parse_memref("55"))
print(parser.parse_memref("5foo"))
print(parser.parse_memref("foo5"))
print(parser.parse_memref("foo_5"))
print(parser.parse_memref("_foo5"))
print(parser.parse_memref("[5]"))
print(parser.parse_memref("[55]"))
print(parser.parse_memref("[foo]"))
print(parser.parse_memref("[foo5]"))
